# Generated by Django 3.2.7 on 2021-10-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='birth_place',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cook',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='cook',
            name='payment_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cook',
            name='work_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
