# Generated by Django 3.2.7 on 2021-10-06 11:13

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cook',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
