# Generated by Django 3.2.7 on 2021-10-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0002_alter_cook_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='is_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
