<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-10-05 13:09
=======
# Generated by Django 3.2.7 on 2021-10-06 07:20
>>>>>>> Deployment

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('orders', '0001_initial'),
>>>>>>> Deployment
        ('clients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('transport', models.CharField(blank=True, max_length=150, null=True)),
                ('work_experience', models.IntegerField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('is_available', models.BooleanField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
            ],
            options={
                'verbose_name': 'Courier',
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_area', models.CharField(blank=True, max_length=150, null=True)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_services', to='clients.client')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_services', to='delivery.courier')),
            ],
        ),
    ]
