# Generated by Django 3.2.7 on 2021-10-11 09:01

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('transport', models.CharField(blank=True, max_length=150, null=True)),
                ('work_experience', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('is_available', models.BooleanField(blank=True, default=False, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Courier',
            },
            bases=('users.user',),
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_area', models.CharField(blank=True, max_length=150, null=True)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_services', to='clients.client')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_services', to='delivery.courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_services', to='orders.order')),
            ],
        ),
        migrations.AddField(
            model_name='courier',
            name='deliveryArea',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='meals', to='delivery.DeliveryArea'),
        ),
    ]
