# Generated by Django 3.2.7 on 2021-10-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='is_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='work_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
