# Generated by Django 3.2.7 on 2021-10-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_courier_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryarea',
            name='courier',
        ),
        migrations.AddField(
            model_name='courier',
            name='deliveryArea',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='meals', to='delivery.DeliveryArea'),
        ),
    ]
