# Generated by Django 3.2.7 on 2021-10-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20211007_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='longitude',
        ),
        migrations.AddField(
            model_name='courier',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='is_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
