# Generated by Django 3.2.7 on 2021-10-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'Cook'), ('2', 'Supplier')], default='1', max_length=2),
        ),
    ]
