# Generated by Django 3.2.7 on 2021-10-05 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '994709616909'. Up to 12 digits", regex='^994(?:50|51|55|70|77|99|10|60)[0-9]{7}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'Cook'), ('2', 'Supplier')], default='1', max_length=2),
        ),
    ]
