# Generated by Django 3.2.7 on 2021-10-06 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211006_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '994709616969'. Up to 12 digits", regex='^994(?:50|51|55|70|77|99|10|60)[0-9]{7}$')]),
        ),
    ]
