version: '2.4'

services:

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - "web"
    volumes:
      - ./static/:/code/static/
      - ./media/:/code/media/

  # postgres:
  #   image: postgres:9.6.6
  #   restart: always
  #   volumes:
  #       - ./pgdb/:/var/lib/postgresql/
  #   ports:
  #       - "5432:5432"
  #   env_file: ./.env

  web:
    container_name: lezzet
    image: lezzetly_web
    build: .
    restart: "always"
    ports:
        - "8000:8000"
    
    volumes:
        - .:/code/
    # depends_on:
    #     - "postgres"
    env_file: ./.env

networks:
  default:
    name: client_default

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
