version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: lezzetly123
      POSTGRES_USER: lezzetly
      POSTGRES_DB: db_name


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080