version: '3.1'

services:

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - "web"
    volumes:
      - ./static/:/code/static/
      - ./media/:/code/media/

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: ./.env

  web:
    build: .
    restart: always
    ports: 
      - "8000:8000"
    volumes:
      - .:/code
      - ./static/:/code/static/
    depends_on: 
      - "db"
    environment:
      - VIRTUAL_HOST=localhost,34.89.135.58 #add your deployment ip from google cloud
      - VIRTUAL_PORT=8000
      - HTTP_PORT=8000


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080