# Generated by Django 3.2.7 on 2021-10-08 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cook'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_first_name',
            field=models.CharField(default=1, max_length=150, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_last_name',
            field=models.CharField(default=1, max_length=150, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default=994502702569, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '994709616969'. Up to 12 digits", regex='^994(?:50|51|55|70|77|99|10|60)[0-9]{7}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Order is confirmed by cook'), ('2', 'Preparing order'), ('3', 'Order is ready'), ('4', 'Courier took order'), ('5', 'Courier is on the to you'), ('6', 'Order is here!')], max_length=2, null=True),
        ),
    ]
